package com.spc.nutricoach.ui.theme

import androidx.compose.ui.graphics.Color

// Vital Wellness (Light Mode)
val vw_primary = Color(0xFF426446)
val vw_onPrimary = Color(0xFFFFFFFF)
val vw_primaryContainer = Color(0xFF5a7d5d)
val vw_onPrimaryContainer = Color(0xFFf7fff2)
val vw_secondary = Color(0xFF49654d)
val vw_onSecondary = Color(0xFFFFFFFF)
val vw_secondaryContainer = Color(0xFFcaebcc)
val vw_onSecondaryContainer = Color(0xFF4e6b53)
val vw_tertiary = Color(0xFF5e5c52)
val vw_onTertiary = Color(0xFFFFFFFF)
val vw_tertiaryContainer = Color(0xFF777569)
val vw_onTertiaryContainer = Color(0xFFfffbff)
val vw_error = Color(0xFFba1a1a)
val vw_onError = Color(0xFFFFFFFF)
val vw_errorContainer = Color(0xFFffdad6)
val vw_onErrorContainer = Color(0xFF93000a)
val vw_background = Color(0xFFfbf9f8)
val vw_onBackground = Color(0xFF1b1c1c)
val vw_surface = Color(0xFFfbf9f8)
val vw_onSurface = Color(0xFF1b1c1c)
val vw_surfaceVariant = Color(0xFFe4e2e2)
val vw_onSurfaceVariant = Color(0xFF424841)
val vw_outline = Color(0xFF727971)

// Human Tech (Dark Mode)
val ht_primary = Color(0xFFc0c1ff)
val ht_onPrimary = Color(0xFF1000a9)
val ht_primaryContainer = Color(0xFF8083ff)
val ht_onPrimaryContainer = Color(0xFF0d0096)
val ht_secondary = Color(0xFFd3bbff)
val ht_onSecondary = Color(0xFF3f0689)
val ht_secondaryContainer = Color(0xFF592da2)
val ht_onSecondaryContainer = Color(0xFFc8aaff)
val ht_tertiary = Color(0xFF4cd7f6)
val ht_onTertiary = Color(0xFF003640)
val ht_tertiaryContainer = Color(0xFF009eb9)
val ht_onTertiaryContainer = Color(0xFF002f38)
val ht_error = Color(0xFFffb4ab)
val ht_onError = Color(0xFF690005)
val ht_errorContainer = Color(0xFF93000a)
val ht_onErrorContainer = Color(0xFFffdad6)
val ht_background = Color(0xFF0b1326)
val ht_onBackground = Color(0xFFdae2fd)
val ht_surface = Color(0xFF0b1326)
val ht_onSurface = Color(0xFFdae2fd)
val ht_surfaceVariant = Color(0xFF2d3449)
val ht_onSurfaceVariant = Color(0xFFc7c4d7)
val ht_outline = Color(0xFF908fa0)
